apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-authentication-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: api-authentication
    template:
        metadata:
            labels:
                app: api-authentication
        spec:
            containers:
                - name: api-authentication
                  image: docker.io/leandro.cunha/api-authentication:latest
                  ports:
                      - containerPort: 80
